# Generated by Django 4.1.7 on 2023-06-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_shop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='temp_login_token',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
