# Generated by Django 4.1.7 on 2023-06-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_shop_temp_login_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signup_origin',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('direct', 'Direct Registration')], default='shopify', max_length=10),
        ),
    ]
