# Generated by Django 4.2.2 on 2023-06-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
