# Generated by Django 4.2.2 on 2023-07-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_card_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
