# Generated by Django 4.1.7 on 2023-07-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('STRIPE', 'Stripe'), ('SHOPIFY', 'Shopify')], max_length=150, null=True),
        ),
    ]
