# Generated by Django 4.2.2 on 2023-07-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_customuser_payment_provider_and_more'),
        ('authentication', '0008_customuser_created_at_customuser_updated_at'),
    ]

    operations = [
    ]
