# Generated by Django 4.2.2 on 2023-07-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_merge_20230718_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('shopify', 'Shopify')], max_length=150, null=True),
        ),
    ]
