# Generated by Django 4.2.2 on 2024-03-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='legacy_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='legacy_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
