# Generated by Django 4.2.2 on 2024-07-15 17:36

from itertools import islice
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_user_shop_connection(apps, schema_editor):
    Shop = apps.get_model('authentication', 'Shop')
    UserShopConnection = apps.get_model('authentication', 'UserShopConnection')

    shops = Shop.objects.select_related('owner').all()

    batch_size = 10_000
    objs = (UserShopConnection(shop_url=shop.url, owner=shop.owner)
            for shop in shops)

    while True:
        batch = list(islice(objs, batch_size))
        if not batch:
            break
        UserShopConnection.objects.bulk_create(batch, batch_size, ignore_conflicts=True)


def reverse_user_shop_connection(apps, schema_editor):
    UserShopConnection = apps.get_model('authentication', 'UserShopConnection')
    UserShopConnection.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_userreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShopConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.TextField()),
                ('owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='usershopconnection',
            constraint=models.UniqueConstraint(
                fields=('shop_url', 'owner'), name='unique_store_owner'),
        ),
        migrations.RunPython(populate_user_shop_connection,
                             reverse_user_shop_connection),
    ]
