# Generated by Django 4.2.2 on 2024-08-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_usershopconnection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='send_customer_io_emails',
            field=models.BooleanField(default=True, help_text='If unchecked, user will not receive any emails from Customer.io', verbose_name='Send Customer.io emails'),
        ),
    ]
