# Generated by Django 4.2.2 on 2024-08-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_usershopconnection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ps_xid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
