# Generated by Django 4.2.2 on 2024-08-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_customuser_ps_xid'),
        ('authentication', '0013_customuser_send_customer_io_emails'),
    ]

    operations = [
    ]
