# Generated by Django 4.2.2 on 2024-08-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_merge_20240826_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='onboarding_choices',
            field=models.JSONField(default=dict),
        )
    ]
