# Generated by Django 4.2.2 on 2024-06-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0026_suborder_stripe_payment_intent_id_and_more'),
        ('authentication', '0014_alter_customuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='+', to='dropshipping.category'),
        ),
    ]
