# Generated by Django 4.2.2 on 2024-08-29 13:16

from django.db import migrations, connection


# Define a list of fields with a name and a SQL subquery to select the correct values to set in the JSON
FIELDS = [
    {"name": "categories", "subquery":
     """
        (SELECT jsonb_agg(category_id)
            FROM authentication_customuser_categories
            WHERE authentication_customuser_categories.customuser_id = authentication_customuser.id
        )
    """}
]

BATCH_SIZE = 5000


def populate_onboarding_choices(apps, schema_editor):
    CustomUser = apps.get_model('authentication', 'CustomUser')
    users_count = CustomUser.objects.count()
    batch_count = users_count // BATCH_SIZE + 1

    for i in range(batch_count):
        start = i * BATCH_SIZE
        end = (i + 1) * BATCH_SIZE

        batch_users = CustomUser.objects.order_by(
            'id').values_list('id', flat=True)[start:end]

        with connection.cursor() as cursor:
            for field in FIELDS:
                cursor.execute(f'''
            UPDATE authentication_customuser
                SET onboarding_choices = jsonb_set(
                    onboarding_choices,
                    '{{{field["name"]}}}',
                    COALESCE(
                        {field["subquery"]},
                        'null'
                    )
                )
                WHERE id = ANY(%s)
            ''', [list(batch_users)])


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_customuser_onboarding_choices'),
    ]

    operations = [
        migrations.RunPython(populate_onboarding_choices)
    ]
