# Generated by Django 4.2.2 on 2024-07-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_usershopconnection_and_more'),
        ('authentication', '0015_customuser_categories'),
    ]

    operations = [
    ]
