# Generated by Django 4.2.2 on 2024-08-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_customuser_ps_xid'),
        ('authentication', '0016_merge_20240716_1906'),
    ]

    operations = [
    ]
