# Generated by Django 4.2.2 on 2024-09-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20240829_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_created_stripe_upgrade_funnel_coupon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_used_stripe_upgrade_funnel_coupon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='send_customer_io_emails',
            field=models.BooleanField(default=True, help_text='If unchecked, user will be removed from Customer.io and will not receive any emails from Customer.io', verbose_name='Send Customer.io emails'),
        ),
    ]
