# Generated by Django 4.2.2 on 2024-09-12 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20240829_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServicePermissionRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_daily_limit_cents', models.IntegerField(default=0, help_text='Daily refund limit in cents.')),
                ('refund_daily_count_limit', models.IntegerField(default=0, help_text='Daily refund count limit.')),
                ('plan_downgrade_limit_annual', models.IntegerField(default=0, help_text='Annual plan downgrade limit.')),
                ('plan_downgrade_limit', models.IntegerField(default=0, help_text='Plan downgrade limit.')),
                ('account_deletion_limit', models.IntegerField(default=0, help_text='Account deletion limit.')),
                ('order_refund_daily_limit_cents', models.IntegerField(default=0, help_text='Daily order refund limit in cents.')),
                ('plan_cancel_limit', models.IntegerField(default=0, help_text='Plan cancel count limit.')),
                ('plan_pause_limit', models.IntegerField(default=0, help_text='Plan pause count limit.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CS Permission Restriction',
            },
        ),
        migrations.CreateModel(
            name='CustomerServiceActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('action', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CS Action Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='customerservicepermissionrestrictions',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user'),
        ),
    ]
