# Generated by Django 4.2.2 on 2024-09-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20240829_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='utm_source',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='utm_term',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='send_customer_io_emails',
            field=models.BooleanField(default=True, help_text='If unchecked, user will be removed from Customer.io and will not receive any emails from Customer.io', verbose_name='Send Customer.io emails'),
        ),
    ]
