# Generated by Django 4.2.2 on 2024-09-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_customuser_utm_campaign_customuser_utm_medium_and_more'),
        ('authentication', '0017_merge_0013_customuser_ps_xid_0016_merge_20240716_1906'),
    ]

    operations = [
    ]
