# Generated by Django 4.2.2 on 2024-09-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_customuser_utm_campaign_customuser_utm_medium_and_more'),
        ('authentication', '0018_create_cs_group'),
    ]

    operations = [
    ]
