# Generated by Django 4.2.2 on 2024-09-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_customuser_has_used_stripe_upgrade_funnel_coupon_and_more'),
        ('authentication', '0019_merge_20240916_2015'),
    ]

    operations = [
    ]
