# Generated by Django 4.2.2 on 2024-09-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_merge_20240913_1733'),
        ('authentication', '0019_merge_20240916_2015'),
    ]

    operations = [
    ]
