# Generated by Django 4.2.2 on 2024-10-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_merge_20240918_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_card_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
