# Generated by Django 4.2.2 on 2024-10-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_merge_20240918_1819'),
        ('authentication', '0020_merge_20240923_1933'),
    ]

    operations = [
    ]
