# Generated by Django 4.2.2 on 2024-11-06 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_customuser_stripe_card_updated_at'),
        ('authentication', '0021_merge_20241010_1918'),
    ]

    operations = [
    ]
