# Generated by Django 4.2.2 on 2026-01-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_customuser_utm_adgroup_customuser_utm_assetgroupid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='utm_country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='utm_os',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='utm_province',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
