# Generated by Django 4.2.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_customuser_utm_country_customuser_utm_os_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPasskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(db_index=True, max_length=256, unique=True)),
                ('public_key', models.BinaryField()),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_passkeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Passkey',
                'verbose_name_plural': 'Admin Passkeys',
            },
        ),
    ]
