# Generated by Django 4.2.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0028_adminpasskey"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerservicepermissionrestrictions",
            name="can_extend_trial",
            field=models.BooleanField(
                default=False,
                help_text="Allow extending trials from admin.",
            ),
        ),
    ]

