# Generated by Django 4.2.2 on 2024-05-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='primary_action_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='secondary_action_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
