# Generated by Django 4.1.7 on 2023-06-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('IN', 'Inactive')], default='AC', max_length=2)),
                ('cost_per_month', models.IntegerField()),
                ('old_cost_per_month', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('features', models.JSONField(default=list)),
                ('limits', models.JSONField(default=dict)),
                ('trial_days', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100, null=True)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('months_off', models.IntegerField(default=0)),
            ],
        ),
    ]
