# Generated by Django 4.1.7 on 2023-06-15 18:59

from django.db import migrations


def add_subscription_plans(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    SubscriptionPlan = apps.get_model('billing', 'SubscriptionPlan')

    starter_features = []


    pro_features = []

    empire_features = []

    unicorn_features = []

    plans = [
        {
            "name": "Starter",
            "period": "monthly",
            "cost_per_month": 2900,
            "features": starter_features,
            "limits": {},
            "trial_days": 7,
        },
        {
            "name": "Pro",
            "period": "monthly",
            "cost_per_month": 4900,
            "features": pro_features,
            "limits": {},
            "trial_days": 7
        },
        {
            "name": "Empire",
            "period": "monthly",
            "cost_per_month": 9900,
            "features": empire_features,
            "limits": {},
            "trial_days": 7,
            "is_highlighted": True,
        },
        {
            "name": "Unicorn",
            "period": "monthly",
            "cost_per_month": 29900,
            "features": unicorn_features,
            "limits": {},
            "trial_days": 7,
        },
        {
            "name": "Pro",
            "period": "yearly",
            "cost_per_month": 2400,
            "old_cost_per_month": 4900,
            "features": pro_features,
            "limits": {},
            "months_off": 6
        },
        {
            "name": "Empire",
            "period": "yearly",
            "cost_per_month": 5700,
            "old_cost_per_month": 9900,
            "features": empire_features,
            "limits": {},
            "months_off": 5,
            "is_highlighted": True,
        },
        {
            "name": "Unicorn",
            "period": "yearly",
            "cost_per_month": 9900,
            "old_cost_per_month": 29900,
            "features": unicorn_features,
            "limits": {},
            "months_off": 8
        }
    ]

    for plan in plans:
        SubscriptionPlan.objects.create(**plan)


def delete_subscription_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('billing', 'SubscriptionPlan')
    SubscriptionPlan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscriptionplan'),
    ]

    operations = [
        migrations.RunPython(add_subscription_plans, delete_subscription_plans),
    ]
