# Generated by Django 4.1.7 on 2023-06-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20230615_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='period',
            new_name='interval',
        ),
    ]
