# Generated by Django 4.1.7 on 2023-06-20 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_signup_origin'),
        ('billing', '0005_alter_subscriptionplan_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'Active'), ('IN', 'Inactive')], default='IN', max_length=2)),
                ('external_id', models.CharField(max_length=100, null=True)),
                ('payment_provider', models.CharField(choices=[('stripe', 'Stripe'), ('shopify', 'Shopify')], default='shopify', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.subscriptionplan')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.shop')),
            ],
        ),
    ]
