# Generated by Django 4.1.7 on 2023-06-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_plan_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
