# Generated by Django 4.2.2 on 2023-07-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_subscriptionplan_interval'),
        ('billing', '0008_appsetting'),
    ]

    operations = [
    ]
