# Generated by Django 4.2.2 on 2023-07-21 15:11

from django.db import migrations


def add_app_setting(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    AppSetting = apps.get_model('billing', 'AppSetting')
    AppSetting.objects.create(stripe_percentage=0)


def delete_app_setting(apps, schema_editor):
    AppSetting = apps.get_model('billing', 'AppSetting')
    AppSetting.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_merge_20230718_1307'),
    ]

    operations = [
        migrations.RunPython(add_app_setting, delete_app_setting),
    ]
