# Generated by Django 4.2.2 on 2023-12-04 18:19
# INFO: Update pricing plan prices.

from django.db import migrations

def delete_the_default_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('billing', 'SubscriptionPlan')
    SubscriptionPlan.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20230721_1511'),
    ]

    operations = [
        migrations.RunPython(delete_the_default_plans),
    ]
