# Generated by Django 4.2.2 on 2024-03-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_auto_20231204_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='legacy_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='legacy_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
