# Generated by Django 4.2.2 on 2024-04-05 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_userreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0014_subscription_legacy_id_subscriptionplan_legacy_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('cancelled', 'Cancelled'), ('upgraded', 'Upgraded'), ('downgraded', 'Downgraded'), ('resumed', 'Resumed'), ('paused', 'Paused'), ('trialing', 'Trialing'), ('activated', 'Activated'), ('scheduled_to_cancel', 'Scheduled to Cancel'), ('trial_cancelled', 'Trial Cancelled')], default='activated', max_length=25)),
                ('payment_provider', models.CharField(choices=[('stripe', 'Stripe'), ('shopify', 'Shopify')], default='stripe', max_length=10)),
                ('period_end', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.subscriptionplan')),
                ('previous_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.subscriptionplan')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.shop')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscription')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('refund', 'Refund'), ('payment', 'Payment')], default='payment', max_length=15)),
                ('entity_type', models.CharField(choices=[('subscription', 'Subscription'), ('one_time', 'One Time')], default='subscription', max_length=15)),
                ('entity_external_id', models.CharField(blank=True, max_length=150, null=True)),
                ('payment_external_id', models.CharField(blank=True, max_length=150, null=True)),
                ('invoice_external_id', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.IntegerField()),
                ('payment_provider', models.CharField(choices=[('stripe', 'Stripe'), ('shopify', 'Shopify')], default='stripe', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.shop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
