# Generated by Django 4.2.2 on 2024-04-05 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_subscriptionhistory_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='invoice_pdf',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
