# Generated by Django 4.2.2 on 2024-04-08 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_userreview'),
        ('billing', '0015_paymenthistory_invoice_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.shop'),
        ),
    ]
