# Generated by Django 4.2.2 on 2024-04-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_subscription_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='period_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='subscription_created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
