# Generated by Django 4.2.2 on 2024-04-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_paymenthistory_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('PA', 'Paused'), ('IN', 'Inactive')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('PA', 'Paused'), ('IN', 'Inactive')], default='AC', max_length=2),
        ),
    ]
