# Generated by Django 4.2.2 on 2024-04-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_alter_subscription_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
