# Generated by Django 4.2.2 on 2024-04-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_subscription_paused_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='action',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('upgraded', 'Upgraded'), ('downgraded', 'Downgraded'), ('resumed', 'Resumed'), ('paused', 'Paused'), ('trialing', 'Trialing'), ('activated', 'Activated'), ('scheduled_to_cancel', 'Scheduled to Cancel'), ('trial_cancelled', 'Trial Cancelled'), ('incomplete', 'Incomplete'), ('past_due', 'Past Due')], default='activated', max_length=25),
        ),
    ]
