# Generated by Django 4.2.2 on 2024-04-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_subscription_cancel_at_subscription_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
