# Generated by Django 4.2.2 on 2024-04-19 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_subscriptionhistory_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionhistory',
            name='cancelled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='trial_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='trial_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
