# Generated by Django 4.1.7 on 2023-06-15 18:59

from django.db import migrations
from billing.models import ActiveStatus, SubscriptionIntervals
from django.core.management import call_command


def add_subscription_plans(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    SubscriptionPlan = apps.get_model('billing', 'SubscriptionPlan')

    starter_features = ["<b>250</b> unique products", "Personalized branding", "<b>Branded</b> Invoicing"]
    pro_features = ["<b>250</b> unique products", "<b>25</b> premium products", "<b>Customize</b> product image background", "<b>24/7</b> Chat & Email Support"]
    empire_features = ["<b>1,000</b> unique products", "<b>250</b> premium products", "<b>VIP</b> Chat & Email Support"]
    unicorn_features = ["<b>Unlimited</b> unique products", "<b>Unlimited</b> premium products", "<b>VIP</b> Chat & Email Support"]

    starter_limits = {"live_products": 250, "branded_invoice": True, "premium_products": 0, "personalized_branding": True, "customized_product_image_background": False}
    pro_limits = {"live_products": 250, "branded_invoice": True, "premium_products": 25, "personalized_branding": True, "customized_product_image_background": True}
    empire_limits = {"live_products": 1000, "branded_invoice": True, "premium_products": 250, "personalized_branding": True, "customized_product_image_background": True}
    unicorn_limits = {"live_products": 1000000, "branded_invoice": True, "premium_products": 1000000, "personalized_branding": True, "customized_product_image_background": True}

    plans = [
        {
            "name": "Starter",
            "interval": SubscriptionIntervals.MONTHLY,
            "cost_per_month": 2900,
            "features": starter_features,
            "limits": starter_limits,
            "trial_days": 7,
        },
        {
            "name": "Pro",
            "interval": SubscriptionIntervals.MONTHLY,
            "cost_per_month": 4900,
            "features": pro_features,
            "limits": pro_limits,
            "trial_days": 7
        },
        {
            "name": "Empire",
            "interval": SubscriptionIntervals.MONTHLY,
            "cost_per_month": 9900,
            "features": empire_features,
            "limits": empire_limits,
            "trial_days": 7,
            "is_highlighted": True,
        },
        {
            "name": "Unicorn",
            "interval": SubscriptionIntervals.MONTHLY,
            "cost_per_month": 29900,
            "features": unicorn_features,
            "limits": unicorn_limits,
            "trial_days": 7,
        },
        {
            "name": "Pro",
            "interval": SubscriptionIntervals.YEARLY,
            "cost_per_month": 2400,
            "old_cost_per_month": 4900,
            "features": pro_features,
            "limits": pro_limits,
            "months_off": 6
        },
        {
            "name": "Empire",
            "interval": SubscriptionIntervals.YEARLY,
            "cost_per_month": 5700,
            "old_cost_per_month": 9900,
            "features": empire_features,
            "limits": empire_limits,
            "months_off": 5,
            "is_highlighted": True,
        },
        {
            "name": "Unicorn",
            "interval": SubscriptionIntervals.YEARLY,
            "cost_per_month": 9900,
            "old_cost_per_month": 29900,
            "features": unicorn_features,
            "limits": unicorn_limits,
            "months_off": 8
        }
    ]

    existing_plans = SubscriptionPlan.objects.all()

    for plan in existing_plans:
        plan.status = ActiveStatus.INACTIVE
        plan.save()

    for plan in plans:
        SubscriptionPlan.objects.create(**plan)

    call_command('create_stripe_plans')


def delete_subscription_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('billing', 'SubscriptionPlan')
    SubscriptionPlan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_subscriptionhistory_cancelled_at_and_more'),
    ]

    operations = [
        migrations.RunPython(add_subscription_plans, delete_subscription_plans),
    ]
