# Generated by Django 4.2.2 on 2024-05-07 13:39

from django.db import migrations


def forwards_func(apps, schema_editor):
    Subscription = apps.get_model('billing', 'Subscription')
    for subscription in Subscription.objects.all():
        if not subscription.shop:
            continue
        subscription.user = subscription.shop.owner
        subscription.save()


def reverse_func(apps, schema_editor):
    Subscription = apps.get_model('billing', 'Subscription')
    Shop = apps.get_model('authentication', 'Shop')
    for subscription in Subscription.objects.all():
        if subscription.shop:
            continue
        subscription.shop = Shop.objects.filter(owner=subscription.user).first()
        subscription.save()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_subscription_user'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
