# Generated by Django 4.2.2 on 2024-06-06 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_customuser_categories'),
        ('billing', '0025_auto_20240509_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.shop'),
        ),
    ]
