# Generated by Django 4.2.2 on 2024-08-05 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0027_appsetting_stripe_cancel_on_uninstall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('billing', 'Billing'), ('features', 'Features'), ('expensive', 'Expensive'), ('not_sure', 'Not sure'), ('other', 'Other')], default='other', max_length=15)),
                ('returning', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
