# Generated by Django 4.2.2 on 2024-06-18 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_userreview'),
        ('billing', '0026_alter_subscription_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='stripe_cancel_on_uninstall',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.shop'),
        ),
    ]
