# Generated by Django 4.2.2 on 2024-07-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_appsetting_stripe_cancel_on_uninstall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_method',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
