# Generated by Django 4.2.2 on 2024-08-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_paymenthistory_payment_method'),
        ('billing', '0027_subscriptioncancellation'),
    ]

    operations = [
    ]
