# Generated by Django 4.2.2 on 2024-09-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_merge_20240805_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('PA', 'Paused'), ('IN', 'Inactive'), ('PD', 'Past Due')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('PA', 'Paused'), ('IN', 'Inactive'), ('PD', 'Past Due')], default='AC', max_length=2),
        ),
    ]
