# Generated by Django 4.2.2 on 2024-09-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_alter_subscription_status_and_more'),
        ('billing', '0028_merge_20240805_1804'),
    ]

    operations = [
    ]
