# Generated by Django 4.2.2 on 2024-09-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_alter_subscription_status_and_more'),
        ('billing', '0029_merge_20240912_1144'),
    ]

    operations = [
    ]
