# Generated by Django 4.2.2 on 2024-09-12 14:48

from django.db import migrations
import stripe

from billing.models import SubscriptionIntervals


def create_coupon_for_plan(apps, plan_name: str, duration_in_months: int, percent_off: int):
    SubscriptionPlan = apps.get_model('billing', 'SubscriptionPlan')
    plans = SubscriptionPlan.objects.filter(name=plan_name,
                                            interval=SubscriptionIntervals.MONTHLY,
                                            stripe_plan_id__isnull=False)

    stripe_plans = []
    for plan in plans:
        try:
            stripe_plan = stripe.Plan.retrieve(plan.stripe_plan_id)
            stripe_plans.append(stripe_plan)
        except:
            pass

    coupon = stripe.Coupon.create(
        duration="repeating",
        duration_in_months=duration_in_months,
        percent_off=percent_off,
        name=f"{plan_name} upgrade discount",
        applies_to={"products": [
            stripe_plan.product for stripe_plan in stripe_plans]}
    )

    plans.update(stripe_upgrade_funnel_coupon_id=coupon.id,
                 stripe_upgrade_funnel_coupon_code="UPGRADE")


def create_coupons(apps, schema_editor):
    create_coupon_for_plan(
        apps,
        "Empire",
        duration_in_months=3,
        percent_off=20)

    create_coupon_for_plan(
        apps,
        "Unicorn",
        duration_in_months=3,
        percent_off=33)


def delete_coupons(apps, schema_editor):
    SubscriptionPlan = apps.get_model('billing', 'SubscriptionPlan')
    plans = SubscriptionPlan.objects.filter(stripe_upgrade_funnel_coupon_id__isnull=False)

    for plan in plans:
        stripe.Coupon.delete(plan.stripe_upgrade_funnel_coupon_id)

    plans.update(stripe_upgrade_funnel_coupon_id=None,
                 stripe_upgrade_funnel_coupon_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_subscriptionplan_stripe_upgrade_funnel_coupon_id_and_more'),
    ]

    operations = [
        migrations.RunPython(create_coupons, delete_coupons),
    ]
