# Generated by Django 4.2.2 on 2024-09-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_create_stripe_coupons'),
        ('billing', '0030_merge_20240916_2014'),
    ]

    operations = [
    ]
