# Generated by Django 4.2.2 on 2024-09-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_merge_20240918_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='paypal_plan_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('shopify', 'Shopify'), ('paypal', 'PayPal')], default='stripe', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('shopify', 'Shopify'), ('paypal', 'PayPal')], default='shopify', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='payment_provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('shopify', 'Shopify'), ('paypal', 'PayPal')], default='stripe', max_length=10),
        ),
    ]
