# Generated by Django 4.2.2 on 2024-10-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_subscriptionplan_paypal_plan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='paypal_webhook_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
