# Generated by Django 4.2.2 on 2024-10-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0033_appsetting_paypal_webhook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='paypal_product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
