# Generated by Django 4.2.2 on 2024-09-27 20:16

from django.db import migrations
from django.core.management import call_command


def create_paypal_plans_command(apps, schema_editor):
    try:
        call_command('create_paypal_plans')
    except:
        print('Plans already exist')


def create_paypal_webhooks_command(apps, schema_editor):
    try:
        call_command('create_paypal_webhooks')
    except:
        print('Webhooks already exist')


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0034_appsetting_paypal_product_id'),
    ]

    operations = [
        # migrations.RunPython(create_paypal_plans_command),
        # migrations.RunPython(create_paypal_webhooks_command)
    ]
