# Generated by Django 4.2.2 on 2024-10-14 17:53

from django.db import migrations
from billing import constants, paypal
from billing.models import ActiveStatus
from dropshipping.helpers import cents_to_string


def remove_trial_fee(apps, schema_editor):
    SubscriptionPlan = apps.get_model('billing', 'SubscriptionPlan')

    if not paypal.is_paypal_configured():
        print("Aborting remove_trial_fee because PayPal is not configured (you need to set the environment variables PAYPAL_BASE_URL, PAYPAL_CLIENT_ID, and PAYPAL_CLIENT_SECRET)")
        return

    plans_with_trial = SubscriptionPlan.objects.filter(
        status=ActiveStatus.ACTIVE,
        trial_days__gt=0,
        paypal_plan_id__isnull=False
    )

    for plan in plans_with_trial:
        pricing_schemes = [
            {
                'billing_cycle_sequence': 1,
                'pricing_scheme': {'fixed_price': {
                    'currency_code': constants.CURRENCY,
                    'value': cents_to_string(0)
                }}
            }
        ]

        paypal.update_pricing(plan.paypal_plan_id, pricing_schemes)

        print(f'Remove trial fee for subscription plan {plan}')


def add_trial_fee(apps, schema_editor):
    SubscriptionPlan = apps.get_model('billing', 'SubscriptionPlan')

    if not paypal.is_paypal_configured():
        print("Aborting add_trial_fee because PayPal is not configured (you need to set the environment variables PAYPAL_BASE_URL, PAYPAL_CLIENT_ID, and PAYPAL_CLIENT_SECRET)")
        return

    plans_with_trial = SubscriptionPlan.objects.filter(
        status=ActiveStatus.ACTIVE,
        trial_days__gt=0,
        paypal_plan_id__isnull=False
    )

    for plan in plans_with_trial:
        pricing_schemes = [
            {
                'billing_cycle_sequence': 1,
                'pricing_scheme': {'fixed_price': {
                    'currency_code': constants.CURRENCY,
                    'value': cents_to_string(constants.TRIAL_INITIAL_COST_CENTS)
                }}
            }
        ]

        paypal.update_pricing(plan.paypal_plan_id, pricing_schemes)

        print(f'Successfully added trial fee for subscription plan {plan}')


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0035_create_paypal_plans'),
    ]

    operations = [
        migrations.RunPython(remove_trial_fee, add_trial_fee),
    ]
