# Generated by Django 4.2.2 on 2024-10-21 13:30

import json
from django.db import migrations

from billing.models import ActiveStatus, SubscriptionIntervals
import stripe
from billing import constants, paypal
from billing.utils import get_plan_name
from dropshipping.helpers import cents_to_string


def update_unicorn_annual_price(apps, schema_editor):
    SubscriptionPlan = apps.get_model('billing', 'SubscriptionPlan')

    new_cost_per_month_cents = 6900
    new_annual_cost_cents = new_cost_per_month_cents * 12

    annual_unicorn_plan = SubscriptionPlan.objects.filter(name="Unicorn",
                                                          interval=SubscriptionIntervals.YEARLY,
                                                          status=ActiveStatus.ACTIVE).first()

    if annual_unicorn_plan.stripe_plan_id:
        stripe_plan = stripe.Plan.create(
            amount=new_annual_cost_cents,
            currency='usd',
            interval='year',
            product={'name': get_plan_name(annual_unicorn_plan)},
            metadata={
                'features': json.dumps(annual_unicorn_plan.features),
                'limits': json.dumps(annual_unicorn_plan.limits),
            },
            trial_period_days=0
        )

        annual_unicorn_plan.stripe_plan_id = stripe_plan.id

    if annual_unicorn_plan.paypal_plan_id:
        paypal.update_pricing(annual_unicorn_plan.paypal_plan_id, [
            {
                'billing_cycle_sequence': 1,
                'pricing_scheme': {
                    'fixed_price': {
                        'currency_code': constants.CURRENCY,
                        'value': cents_to_string(new_annual_cost_cents)
                    }
                }
            }
        ])

    annual_unicorn_plan.cost_per_month = new_cost_per_month_cents
    annual_unicorn_plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0036_auto_20241014_1753'),
    ]

    operations = [
        migrations.RunPython(update_unicorn_annual_price),
    ]
