# Generated by Django 4.2.2 on 2024-10-30 14:21

from django.db import migrations
from django.core.management import call_command


def create_paypal_plans_command(apps, schema_editor):
    try:
        call_command('create_paypal_plans')
    except Exception as e:
        print('Error creating PayPal plans', e)


def create_paypal_webhooks_command(apps, schema_editor):
    try:
        call_command('create_paypal_webhooks')
    except Exception as e:
        print('Error creating PayPal webhooks', e)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0037_auto_20241021_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsetting',
            name='paypal_product_id',
        ),

        migrations.RunPython(create_paypal_plans_command),
        migrations.RunPython(create_paypal_webhooks_command)
    ]
