"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this files, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from datetime import datetime

import ddtrace.auto
import os
from pathlib import Path
from urllib.parse import quote, urlparse
import environ
import stripe
from corsheaders.defaults import default_headers
from celery.schedules import crontab
from customerio import CustomerIO, Regions
import base64

CORS_ALLOW_HEADERS = list(default_headers) + [
    'baggage',
]
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, True)
)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env files
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

FRONTEND_URL = env("FRONTEND_URL")
API_URL = env("API_URL")

# CSRF origins:
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8100',
    'http://localhost:8020',
    'http://localhost:8010',
    'http://localhost:8000',
    'http://127.0.0.1:8100',
    'http://127.0.0.1:8020',
    'http://127.0.0.1:8010',
    'http://127.0.0.1:8000',
    API_URL
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET")
SECRET_KEY_FALLBACKS = ['django-insecure-ox3u(69_q+@s3u=c!2(af=rdyyqh2to3fwar+gehk*-_5=49a9']

DEBUG = env('DEBUG', default=False)

ALLOWED_HOSTS = [
    "*"
]

SITE_ID = 1
# Application definition
INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'rest_framework.authtoken',
    'dj_rest_auth.registration',
    'dj_rest_auth',
    'django_celery_results',
    'django_celery_beat',
    "corsheaders",
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'authentication',
    'file',
    'billing',
    'webhooks',
    'shopify_integration',
    'dropshipping',
    'notifications',
    'ai'
]


REST_AUTH = {
    'USER_DETAILS_SERIALIZER': 'authentication.serializers.CustomUserSerializer',
    'USE_JWT': True,
    'OLD_PASSWORD_FIELD_ENABLED': True,
    'LOGOUT_ON_PASSWORD_CHANGE': False,
    'JWT_AUTH_HTTPONLY': False
}

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
    ),
    'PAGE_SIZE': 20
}

REST_USE_JWT = True
JWT_AUTH_COOKIE = None

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    "django.middleware.common.CommonMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middlewares.current_user_middleware.CurrentUserMiddleware',
    'core.middlewares.admin_2fa_middleware.Admin2FAMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

CSRF_COOKIE_SECURE = False  # Set this to True for production if you are using https
# Set this to True for production if you are using https
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
# If using subdomains, set this to your base domain starting with a dot
CSRF_COOKIE_DOMAIN = None

ROOT_URLCONF = 'core.urls'

if not DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'level': 'DEBUG',
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'DEBUG',
            }
        },
        'ddtrace': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    }

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

SECURE_SSL_REDIRECT = False

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8100',
    API_URL,
    FRONTEND_URL
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

AUTH_USER_MODEL = "authentication.CustomUser"
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = '/?verification=1'
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/?verification=1'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_ON_GET = True

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_ADAPTER = 'authentication.adapters.CustomSocialAccountAdapter'
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APPS': [
            {
                'client_id': env('GOOGLE_OAUTH_ID', default=None),
                'secret': env('GOOGLE_OAUTH_SECRET', default=None),
                'key': '',
            },
        ],
        'SCOPE': ['profile', 'email', 'https://www.googleapis.com/auth/drive'],
        'AUTH_PARAMS': {
            'access_type': 'offline',
            'prompt': 'consent'
        },
    },
    'facebook': {
        'METHOD': 'oauth2',
        'APPS': [
            {
                'client_id': env('FACEBOOK_OAUTH_ID', default=None),
                'secret': env('FACEBOOK_OAUTH_SECRET', default=None),
                'key': '',
            },
        ],
        'FIELDS': ['name', 'email'],
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
    }
}

SITE_ID = 1
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env("POSTGRES_DB"),
        'USER': env("POSTGRES_USER"),
        'PASSWORD': env("POSTGRES_PASSWORD"),
        'HOST': env("POSTGRES_HOST"),
        'PORT': env("POSTGRES_PORT"),
    }
}

SHOPIFY_CLIENT_KEY = env("SHOPIFY_CLIENT_KEY")
SHOPIFY_CLIENT_SECRET = env("SHOPIFY_CLIENT_SECRET")
SHOPIFY_API_VERSION = '2025-04'
SHOPIFY_SCOPES = [
    'read_products',
    'write_products',
    'read_orders',
    # Dropshipping required scopes
    'write_fulfillments',
    'read_inventory',
    'write_inventory',
    'read_assigned_fulfillment_orders',
    'read_merchant_managed_fulfillment_orders',
    'read_third_party_fulfillment_orders',
    'write_merchant_managed_fulfillment_orders',
    'write_assigned_fulfillment_orders',
    'write_third_party_fulfillment_orders',
    'read_publications',
    'write_publications'
]

SHOPIFY_NEW_SCOPES = [
    ('read_locations', datetime.strptime(env("READ_LOCATIONS_SCOPE_DATE", default="2025-03-24"), "%Y-%m-%d")),
    ('write_locations', datetime.strptime(env("WRITE_LOCATIONS_SCOPE_DATE", default="2025-03-24"), "%Y-%m-%d")),
]

STRIPE_KEY = env("STRIPE_KEY")
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET", default=None)

if STRIPE_KEY:
    stripe.api_key = STRIPE_KEY

FILE_MAX_SIZE = 1024 * 1024 * 5  # 5MB
FILE_UPLOAD_STORAGE = env("FILE_UPLOAD_STORAGE", default="local")  # local | s3

if FILE_UPLOAD_STORAGE == "local":
    MEDIA_ROOT_NAME = "media"
    MEDIA_ROOT = os.path.join(BASE_DIR, MEDIA_ROOT_NAME)
    MEDIA_URL = f"/{MEDIA_ROOT_NAME}/"

AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_REGION_NAME = env("AWS_REGION_NAME")

if FILE_UPLOAD_STORAGE == "s3":
    # Using django-storages
    # https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

    AWS_S3_ACCESS_KEY_ID = AWS_ACCESS_KEY_ID
    AWS_S3_SECRET_ACCESS_KEY = AWS_SECRET_ACCESS_KEY
    AWS_S3_REGION_NAME = AWS_REGION_NAME
    AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_SIGNATURE_VERSION = env("AWS_S3_SIGNATURE_VERSION", default="s3v4")

    # https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl
    AWS_DEFAULT_ACL = env("AWS_DEFAULT_ACL", default="private")
    AWS_PRESIGNED_EXPIRY = env.int(
        "AWS_PRESIGNED_EXPIRY", default=10)  # seconds

# Bucket should have the following CORS config:
# [{
#     "AllowedHeaders": [
#         "*"
#     ],
#     "AllowedMethods": [
#         "POST"
#     ],
#     "AllowedOrigins": [
#         "*"
#     ],
#     "ExposeHeaders": []
#  }]

PARTNERSTACK_SECRET_KEY = env("PARTNERSTACK_SECRET_KEY", default=None)
APP_NAME = env('APP_NAME', default='jubilee')

BROKER_URL = 'sqs://{access_key}:{secret_key}@'.format(
    access_key=quote(AWS_ACCESS_KEY_ID, safe=''),
    secret_key=quote(AWS_SECRET_ACCESS_KEY, safe=''),
)

SQS_QUEUE_PREFIX = env("DD_ENV", default="staging")
SQS_QUEUE_PREFIX_IMAGE_GENERATION = f"{APP_NAME}-image_generation"

REDIS_CACHE_URL = env('REDIS_CACHE_URL')

ASGI_APPLICATION = "core.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(urlparse(REDIS_CACHE_URL).hostname, 6379)],
            "prefix": f"{APP_NAME}:",
        },
    },
}

BROKER_TRANSPORT_OPTIONS = {
    'region': AWS_REGION_NAME,
    'visibility_timeout': 60,  # 1 minute,
    'polling_interval': 5,      # 5 seconds
    'queue_name_prefix': f'{SQS_QUEUE_PREFIX}-'
}

DG_SECRET = env('DG_SECRET', default='secret')

# CELERY namespaced
CELERY_BROKER_URL = BROKER_URL
CELERY_BROKER_TRANSPORT_OPTIONS = BROKER_TRANSPORT_OPTIONS
CELERY_TASK_DEFAULT_QUEUE = f'{APP_NAME}-default'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_RESULT_EXTENDED = True
CELERY_ENABLE_REMOTE_CONTROL = True

# Worker configurations
CELERY_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50
CELERY_RESULT_EXPIRES = 3600

# CRONS SETUP
CELERY_BEAT_SCHEDULE = {
    "deactivate_expired_subscriptions": {
        "task": "billing.tasks.deactivate_expired_subscriptions",
        "schedule": crontab(minute=0, hour="*/12"),
    },
    "create_end_of_trial_subscription_history": {
        "task": "billing.tasks.create_end_of_trial_subscription_history",
        "schedule": crontab(minute=0, hour="*/12"),
    },
    "deactivate_inactive_products": {
        "task": "dropshipping.tasks.deactivate_inactive_products",
        "schedule": crontab(minute=0, hour="*/2"),
    },
    "send_daily_cs_report": {
        "task": "authentication.tasks.send_daily_cs_report",
        "schedule": crontab(minute=1, hour=0),
    },
    "refund_felex_accounts": {
        "task": "billing.tasks.refund_felex_accounts",
        "schedule": crontab(minute=20, hour=12),
    },
    'cleanup-old-results': {
        'task': 'celery.backend_cleanup',
        'schedule': crontab(hour=2, minute=0),
    },
    "backfill_shopify_ga_utms_every_6h": {
        "task": "authentication.tasks.backfill_shopify_ga_utms",
        "schedule": crontab(minute=0, hour="*/6"),
    },
    "send_trials_kpi_report": {
        "task": "billing.tasks.send_pdf_trials_kpi_report",
        "schedule": crontab(minute=25, hour=6),
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://{urlparse(REDIS_CACHE_URL).hostname}:6379/1",
    }
}

# EMAIL
EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
SENDGRID_API_KEY = env("SENDGRID_API_KEY")
SENDGRID_SANDBOX_MODE_IN_DEBUG = False  # DEBUG
RESET_EMAIL_TEMPLATE_ID = env("RESET_EMAIL_TEMPLATE_ID")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")

NOTIFICATION_API_KEY = env("NOTIFICATION_API_KEY", default=None)

# OPEN AI
OPEN_AI_KEY = env("OPEN_AI_KEY", default=None)
PINECONE_API_KEY = env("PINECONE_API_KEY", default=None)
PINECONE_INDEX_NAME = env("PINECONE_INDEX_NAME", default="embeddings-index")

# DROPSHIPPING
FULFILLMENT_SERVICE_NAME = "Dropshipping App"
INVENTORY_MANAGEMENT = env("INVENTORY_MANAGEMENT", default=False)

TRANSACTION_PERCENTAGE = env("TRANSACTION_PERCENTAGE", default=0.029)
TRANSACTION_FIXED_COST = env("TRANSACTION_FIXED_COST", default=0.3)

CUSTOMER_IO = None
if env("CUSTOMER_IO_SITE_ID", default=None) and env("CUSTOMER_IO_API_KEY", default=None):
    cio = CustomerIO(env("CUSTOMER_IO_SITE_ID", default=None), env(
        "CUSTOMER_IO_API_KEY", default=None), region=Regions.US)
    CUSTOMER_IO = cio


LIST_PER_PAGE = env("LIST_PER_PAGE", default=20)
PAUSE_LIMIT = env("PAUSE_LIMIT", default=2)

ELEVENLABS_API_KEY = env("ELEVENLABS_API_KEY", default=None)
ANTHROPIC_API_KEY = env("ANTHROPIC_API_KEY", default=None)

PAYPAL_PLAN_NAME_PREFIX = env("PAYPAL_PLAN_NAME_PREFIX", default="Jubilee")
PAYPAL_BASE_URL = env(
    "PAYPAL_BASE_URL", default="https://api-m.sandbox.paypal.com" if DEBUG else "https://api-m.paypal.com")
PAYPAL_CLIENT_ID = env("PAYPAL_CLIENT_ID", default=None)
PAYPAL_CLIENT_SECRET = env("PAYPAL_CLIENT_SECRET", default=None)

DISABLE_PAYMENTS = False

SLACK_BOT_TOKEN = env("SLACK_BOT_TOKEN", default=None)
CS_REPORT_SLACK_CHANNEL_ID = env("CS_REPORT_SLACK_CHANNEL_ID", default=None)
SLACK_BOT_TOKEN_KPI = env("SLACK_BOT_TOKEN_KPI", default=None)
KPI_TRIALS_SLACK_CHANNEL_ID = env("KPI_TRIALS_SLACK_CHANNEL_ID", default=None)

CS_REPORT_SERVERS = env("CS_REPORT_SERVERS", default="").split(";")
DISABLE_TRIAL_FEES = env("DISABLE_TRIAL_FEES", default=True)

BRANDED_IMAGE_GENERATION_TTL = int(env("BRANDED_IMAGE_GENERATION_TTL", default=30))

# GOOGLE ANALYTICS
GA4_BQ_PROJECT_ID = env("GA4_BQ_PROJECT_ID", default="")
GA4_BQ_DATASET_ID = env("GA4_BQ_DATASET_ID", default="")
GCP_SERVICE_ACCOUNT_JSON_B64 = env("GCP_SERVICE_ACCOUNT_JSON_B64", default="")
GCP_SERVICE_ACCOUNT_JSON = None
if GCP_SERVICE_ACCOUNT_JSON_B64:
    try:
        GCP_SERVICE_ACCOUNT_JSON = base64.b64decode(GCP_SERVICE_ACCOUNT_JSON_B64).decode("utf-8")
    except Exception:
        pass

# ADMIN 2FA / PASSWORD SECURITY SETTINGS
ADMIN_2FA_ENABLED = env.bool("ADMIN_2FA_ENABLED", default=True)
ADMIN_2FA_RATE_LIMIT_REQUESTS = env.int("ADMIN_2FA_RATE_LIMIT_REQUESTS", default=5)  # per hour
ADMIN_2FA_BACKUP_CODES_COUNT = env.int("ADMIN_2FA_BACKUP_CODES_COUNT", default=10)
ADMIN_2FA_ISSUER_NAME = env("ADMIN_2FA_ISSUER_NAME", default="Jubilee Admin")  # Name shown in authenticator app

# Admin password expiry (in days)
ADMIN_PASSWORD_EXPIRY_DAYS = env.int("ADMIN_PASSWORD_EXPIRY_DAYS", default=28)
