# Generated by Django 4.2.2 on 2024-01-14 17:59

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'description'], name='dropshippin_title_d3d169_gin'),
        ),
    ]
