# Generated by Django 4.2.2 on 2024-01-20 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_userreview'),
        ('file', '0001_initial'),
        ('dropshipping', '0002_product_dropshippin_title_d3d169_gin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('live_at', models.DateTimeField(null=True)),
                ('shopify_product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dropshipping.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_products', to='authentication.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_price_cents', models.IntegerField(blank=True, null=True)),
                ('shopify_variant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shopify_inventory_item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shopify_inventory_level_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_variants', to='dropshipping.importedproduct')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dropshipping.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='DropshipSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_location_id', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_contact_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('invoice_website', models.URLField(blank=True, max_length=255, null=True)),
                ('invoice_body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='file.file')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.shop')),
            ],
        ),
    ]
