# Generated by Django 4.2.2 on 2024-01-25 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_userreview'),
        ('dropshipping', '0004_remove_product_options_remove_product_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shopify_order_name', models.CharField(blank=True, max_length=100, null=True)),
                ('order_type', models.CharField(choices=[('sample_order', 'Sample order'), ('shopify', 'Shopify')], default='shopify', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dropshipping.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='currency',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dropshipping.shipping'),
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost_cents', models.IntegerField()),
                ('shipping_cost_cents', models.IntegerField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=15)),
                ('is_international', models.BooleanField(default=False)),
                ('checkout_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_link', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='dropshipping.order')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.shop')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dropshipping.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dropshipping.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.shop'),
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('sku', models.CharField(max_length=100)),
                ('cost_cents', models.IntegerField(default=0)),
                ('total_cost_cents', models.IntegerField(default=0)),
                ('total_shipping_cost_cents', models.IntegerField(default=0)),
                ('shopify_fulfillment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shopify_product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shopify_variant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dropshipping.product')),
                ('sub_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='dropshipping.suborder')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dropshipping.productvariant')),
            ],
        ),
    ]
