# Generated by Django 4.2.2 on 2024-01-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0005_customer_order_remove_supplier_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropshipsettings',
            name='stripe_card_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='dropshipsettings',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
