# Generated by Django 4.2.2 on 2024-01-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0006_dropshipsettings_stripe_card_digits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropshipsettings',
            name='stripe_card_digits',
        ),
        migrations.RemoveField(
            model_name='dropshipsettings',
            name='stripe_payment_method_id',
        ),
        migrations.AddField(
            model_name='importedproduct',
            name='shopify_product_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
