# Generated by Django 4.2.2 on 2024-02-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0007_remove_dropshipsettings_stripe_card_digits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedvariant',
            name='shopify_available_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
