# Generated by Django 4.2.2 on 2024-02-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0008_importedvariant_shopify_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='shopify_price_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
