# Generated by Django 4.2.2 on 2024-02-16 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_alter_file_uploaded_by'),
        ('dropshipping', '0009_lineitem_shopify_price_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropshipsettings',
            name='invoice_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='file.file'),
        ),
        migrations.AlterField(
            model_name='dropshipsettings',
            name='invoice_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
