# Generated by Django 4.2.2 on 2024-03-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0010_dropshipsettings_invoice_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='legacy_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='legacy_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='legacy_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='legacy_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='legacy_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suborder',
            name='legacy_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='legacy_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
