# Generated by Django 4.2.2 on 2024-03-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0011_category_legacy_id_lineitem_legacy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropshipsettings',
            name='font_family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dropshipsettings',
            name='products_background_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
