# Generated by Django 4.2.2 on 2024-02-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0012_dropshipsettings_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='processing_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='delivery_time',
            field=models.CharField(max_length=10),
        ),
    ]
