# Generated by Django 4.2.2 on 2024-03-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_alter_file_uploaded_by'),
        ('dropshipping', '0013_shipping_processing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productasset',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='file.file'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='file.file'),
        ),
    ]
