# Generated by Django 4.2.2 on 2024-03-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0014_productasset_thumbnail_productvariant_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedproduct',
            name='background_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
