# Generated by Django 4.2.2 on 2024-07-03 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_userreview'),
        ('dropshipping', '0015_importedproduct_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropshipsettings',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.shop'),
        ),
    ]
