# Generated by Django 4.2.2 on 2024-03-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0015_importedproduct_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedproduct',
            name='legacy_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
