# Generated by Django 4.2.2 on 2024-03-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0016_importedproduct_legacy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dropshipping.product'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dropshipping.productvariant'),
        ),
    ]
