# Generated by Django 4.2.2 on 2024-07-04 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_userreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dropshipping', '0016_alter_dropshipsettings_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedproduct',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importedproduct',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_products', to='authentication.shop'),
        ),
    ]
