# Generated by Django 4.2.2 on 2024-07-05 14:12

from django.conf import settings

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0011_userreview"),
        ("dropshipping", "0017_importedproduct_user_alter_importedproduct_shop"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="dropshippin_title_d3d169_gin",
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.shop",
            ),
        ),
        migrations.AlterField(
            model_name="importedproduct",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imported_products",
                to="authentication.shop",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="dropshippin_title_4a6c9a_gin"
            ),
        ),
    ]
