# Generated by Django 4.2.2 on 2024-03-12 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0018_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
