# Generated by Django 4.2.2 on 2024-07-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_userreview'),
        ('dropshipping', '0019_suborder_user_alter_order_user_alter_suborder_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.shop'),
        ),
    ]
