# Generated by Django 4.2.2 on 2024-03-13 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0019_alter_importedproduct_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='X Position')),
                ('y', models.FloatField(verbose_name='Y Position')),
                ('width', models.FloatField(verbose_name='Width')),
                ('height', models.FloatField(verbose_name='Height')),
                ('rotation', models.FloatField(verbose_name='Rotation')),
                ('text_color', models.CharField(max_length=50, verbose_name='Text Color')),
            ],
        ),
        migrations.AddField(
            model_name='productvariant',
            name='brand_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dropshipping.brandsettings'),
        ),
    ]
