# Generated by Django 4.2.2 on 2024-07-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0020_alter_order_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accept_worldwide_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
