# Generated by Django 4.2.2 on 2024-03-15 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_alter_file_uploaded_by'),
        ('dropshipping', '0020_brandsettings_productvariant_brand_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedvariant',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='file.file'),
        ),
        migrations.AddField(
            model_name='importedvariant',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='file.file'),
        ),
    ]
