# Generated by Django 4.2.2 on 2024-03-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0021_importedvariant_image_importedvariant_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropshipsettings',
            name='invoice_website',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
