# Generated by Django 4.2.2 on 2024-07-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0021_alter_suborder_shop'),
        ('dropshipping', '0021_product_accept_worldwide_shipping'),
    ]

    operations = [
    ]
