# Generated by Django 4.2.2 on 2024-03-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0022_alter_dropshipsettings_invoice_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropshipsettings',
            name='distributor_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dropshipsettings',
            name='distributor_zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
