# Generated by Django 4.2.2 on 2024-08-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0023_imagedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
