# Generated by Django 4.2.2 on 2024-04-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0023_dropshipsettings_distributor_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='shopify_moq',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='shopify_moq_price_cents',
            field=models.IntegerField(default=0),
        ),
    ]
