# Generated by Django 4.2.2 on 2024-08-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0023_importedproduct_collections_importedproduct_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedvariant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
