# Generated by Django 4.2.2 on 2024-08-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0023_suborder_is_cancelled'),
        ('dropshipping', '0024_importedvariant_is_active'),
    ]

    operations = [
    ]
