# Generated by Django 4.2.2 on 2024-05-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0024_supplier_shopify_moq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suborder',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]