# Generated by Django 4.2.2 on 2024-05-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0025_suborder_is_processed_suborder_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('processing', 'Processing'), ('refunded', 'Refunded')], default='unpaid', max_length=15),
        ),
    ]
