# Generated by Django 4.2.2 on 2024-06-28 13:41

from itertools import islice
from django.db import migrations, models
import django.db.models.deletion

def populate_product_shipping(apps, schema_editor):
    Product = apps.get_model('dropshipping', 'Product')
    ProductShipping = apps.get_model('dropshipping', 'ProductShipping')

    products = Product.objects.select_related("shipping_domestic", "supplier", "supplier__address").filter(
        shipping_domestic__isnull=False,
        supplier__address__isnull=False)

    batch_size = 10_000
    objs = (ProductShipping(product_id=product.id,
                            shipping_id=product.shipping_domestic.id,
                            country=product.supplier.address.country)
            for product in products)

    while True:
        batch = list(islice(objs, batch_size))
        if not batch:
            break
        ProductShipping.objects.bulk_create(batch, batch_size)


def reverse_product_shipping(apps, schema_editor):
    ProductShipping = apps.get_model('dropshipping', 'ProductShipping')
    ProductShipping.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0027_dropshipsettings_user_alter_dropshipsettings_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropshipping.product')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropshipping.shipping')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productshipping',
            constraint=models.UniqueConstraint(fields=('product', 'country'), name='unique_product_country'),
        ),
        migrations.RunPython(populate_product_shipping, reverse_product_shipping),
        migrations.RenameField(
            model_name='product',
            old_name='shipping_international',
            new_name='shipping_fallback',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_domestic',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='is_international',
        ),
    ]
