# Generated by Django 4.2.2 on 2024-07-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0022_merge_20240708_1856'),
        ('dropshipping', '0028_rename_shipping_international_product_shipping_fallback_and_more'),
    ]

    operations = [
    ]
