# Generated by Django 4.2.2 on 2024-07-03 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dropshipping', '0028_rename_shipping_international_product_shipping_fallback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropshipsettings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
