# Generated by Django 4.2.2 on 2024-07-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0029_merge_20240711_1206'),
        ('dropshipping', '0030_dropshipsettings_user'),
    ]

    operations = [
    ]
