# Generated by Django 4.2.2 on 2024-09-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0025_merge_20240813_1450'),
        ('dropshipping', '0031_merge_20240711_1213'),
    ]

    operations = [
    ]
