# Generated by Django 4.2.2 on 2025-07-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0032_merge_20240913_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dropshipping.product'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dropshipping.productvariant'),
        ),
    ]
