# Generated by Django 4.2.2 on 2024-05-20 18:20
from django.db import migrations
from ai.models import ModelProvider, ModelType


def create_openai_models(apps, schema_editor):
    Model = apps.get_model('ai', 'Model')

    gpt4o = Model(
        name="gpt-4o",
        is_active=True,
        model_type=ModelType.CHAT,
        provider=ModelProvider.OPENAI,
        pricing={"input_cost_per_1k_tokens": 0.005, "output_cost_per_1k_tokens": 0.015},
        default_options={'temperature': 0.8, 'top_p': 0.8, 'max_tokens': 2000, 'frequency_penalty': 0.3, 'presence_penalty': 0.3},
    )
    gpt4o.save()

    gpt3 = Model(
        name='gpt-3.5-turbo-1106',
        is_active=True,
        model_type=ModelType.TEXT,
        provider=ModelProvider.OPENAI,
        pricing={"input_cost_per_1k_tokens": 0.0005, "output_cost_per_1k_tokens": 0.0015},
        default_options={'temperature': 0.8, 'top_p': 0.8, 'max_tokens': 2000, 'frequency_penalty': 0.3, 'presence_penalty': 0.3},
    )
    gpt3.save()

    dalle3_pricing = {
        "1024x1024_standard": 0.040,
        "1024x1792_standard": 0.080,
        "1792x1024_standard": 0.080,
        "1024x1024_hd": 0.080,
        "1024x1792_hd": 0.120,
        "1792x1024_hd": 0.120,
    }
    dalle3 = Model(
        name="dall-e-3",
        is_active=True,
        pricing=dalle3_pricing,
        model_type=ModelType.IMAGE,
        provider=ModelProvider.OPENAI,
        default_options={'quality': 'standard', 'size': '1024x1024', 'n': 1},
    )
    dalle3.save()

    tts = Model(
        name="tts-1",
        is_active=True,
        pricing={"cost_per_1k_characters": 0.015},
        model_type=ModelType.TTS,
        provider=ModelProvider.OPENAI,
        default_options={'voice': 'alloy'},
    )
    tts.save()

    stt = Model(
        name="whisper-1",
        is_active=True,
        pricing={"cost_per_minute": 0.006},
        model_type=ModelType.STT,
        provider=ModelProvider.OPENAI,
        default_options={},
    )
    stt.save()

    embedding = Model(
        name="text-embedding-3-small",
        is_active=True,
        pricing={"cost_per_1k_tokens": 0.00002},
        model_type=ModelType.EMBEDDINGS,
        provider=ModelProvider.OPENAI,
        default_options={},
    )
    embedding.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_openai_models),
    ]
