# Generated by Django 4.2.2 on 2024-05-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_create_openai_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_type',
            field=models.CharField(choices=[('chat', 'chat'), ('text', 'text'), ('image', 'image'), ('video', 'video'), ('tts', 'tts'), ('stt', 'stt'), ('embeddings', 'embeddings')], max_length=255),
        ),
    ]
