# Generated by Django 4.2.2 on 2024-06-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_alter_model_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='provider',
            field=models.CharField(choices=[('openai', 'openai'), ('aws', 'aws'), ('elevenlabs', 'elevenlabs')], max_length=255),
        ),
    ]
