# Generated by Django 4.2.2 on 2024-06-10 20:07

from django.db import migrations
from ai.models import ModelProvider, ModelType


def create_elevenlabs_models(apps, schema_editor):
    Model = apps.get_model('ai', 'Model')

    tts = Model(
        name="eleven_multilingual_v2",
        is_active=True,
        pricing={"cost_per_1k_characters": 0.198},
        model_type=ModelType.TTS,
        provider=ModelProvider.ELEVENLABS,
        default_options={'voice': 'pNInz6obpgDQGcFmaJgB'},
    )
    tts.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_alter_model_provider'),
    ]

    operations = [
        migrations.RunPython(create_elevenlabs_models),
    ]
