# Generated by Django 4.2.2 on 2024-06-12 14:39

from django.db import migrations
from ai.models import ModelProvider, ModelType


def create_aws_models(apps, schema_editor):
    Model = apps.get_model('ai', 'Model')

    tts = Model(
        name="standard",
        is_active=True,
        pricing={"cost_per_1k_characters": 0.004},
        model_type=ModelType.TTS,
        provider=ModelProvider.AWS,
        default_options={'voice': 'Joanna'},
    )
    tts.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_create_elevenlabs_models'),
    ]

    operations = [
        migrations.RunPython(create_aws_models),
    ]
