# Generated by Django 4.2.2 on 2024-07-15 22:52

from django.db import migrations, models
from ai.models import ModelProvider, ModelType


def create_anthropic_models(apps, schema_editor):
    Model = apps.get_model('ai', 'Model')

    text = Model(
        name="claude-3-haiku-20240307",
        is_active=True,
        pricing={"input_cost_per_1k_tokens": 0.00025, "output_cost_per_1k_tokens": 0.00125},
        model_type=ModelType.TEXT,
        provider=ModelProvider.ANTHROPIC,
        default_options={'temperature': 0.8, 'max_tokens': 4096},
    )
    text.save()

    chat = Model(
        name="claude-3-5-sonnet-20240620",
        is_active=True,
        pricing={"input_cost_per_1k_tokens": 0.003, "output_cost_per_1k_tokens": 0.015},
        model_type=ModelType.CHAT,
        provider=ModelProvider.ANTHROPIC,
        default_options={'temperature': 0.8, 'max_tokens': 4096},
    )
    chat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_create_amazon_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='provider',
            field=models.CharField(choices=[('openai', 'openai'), ('aws', 'aws'), ('elevenlabs', 'elevenlabs'), ('anthropic', 'anthropic')], max_length=255),
        ),
        migrations.RunPython(create_anthropic_models),
    ]
