# Generated by Django 4.2.2 on 2024-07-29 14:00

from django.db import migrations
from ai.models import ModelProvider, ModelType


def replace_openai_text_model(apps, schema_editor):
    Model = apps.get_model('ai', 'Model')

    text_model = Model.objects.filter(model_type=ModelType.TEXT, is_active=True, provider=ModelProvider.OPENAI).order_by('-created_at').first()
    text_model.name = "gpt-4o-mini"
    text_model.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_alter_model_provider'),
    ]

    operations = [
        migrations.RunPython(replace_openai_text_model),
    ]
