from django.urls import path, include
from authentication.views import (
    ShopifyCheckPerms,
    ShopifyGetPermanentToken,
    ShopLogin,
    GetShop,
    ForgetPasswordView,
    ResetUserPasswordView,
    ConnectShopify,
    RegisterUser,
    PasswordChangeView,
    LoginView,
    CreateUserReview,
    EditUserView,
    DropGeniusEmailChange,
    FacebookLogin,
    GoogleLogin,
)

urlpatterns = [
    path('shopify_login', ShopifyCheckPerms.as_view(), name='shopify_login'),
    path('shopify_token', ShopifyGetPermanentToken.as_view(), name='shopify_token'),
    path('shop_login/', ShopLogin.as_view(), name="shop_login"),
    path('connect/shopify/', ConnectShopify.as_view(), name="connect_shopify"),
    path('shop/', GetShop.as_view(), name="get_shop"),
    path('dg/email/change/', DropGeniusEmailChange.as_view(), name="dg_change_email"),
    path('auth/password/change/', PasswordChangeView.as_view(), name="change_user_password"),
    path('auth/forget_password/', ForgetPasswordView.as_view(), name="forgot_user_password"),
    path('auth/reset_password/', ResetUserPasswordView.as_view(), name="reset_user_password"),
    path('auth/register/', RegisterUser.as_view(), name="register_user"),
    path('auth/login/', LoginView.as_view(), name="login_user"),
    path('auth/rate/', CreateUserReview.as_view(), name="user_rate"),
    path('auth/edit/', EditUserView.as_view(), name="edit-user"),
    path('auth/', include('dj_rest_auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('auth/registration/', include('dj_rest_auth.registration.urls')),
    path('auth/social/', include('allauth.socialaccount.urls')),
    path('auth/social/facebook/', FacebookLogin.as_view(), name='facebook_login'),
    path('auth/social/google/', GoogleLogin.as_view(), name='google_login'),
]
